### ISSUE TITLE
Support for Node > 10

### ISSUE THREAD

**Issue by christiansaiki** [mithunsatheesh/node-rules#114]
Hi quick question, I was wondering if it's possible to change the engine from Node 10 to support Node >= 10? 

I'm currently using Node 12 and I'm not being able to install `node-rules`

```
Christians-MBP sls-services (master) $ yarn add node-rules
yarn add v1.22.4
[1/5] 🔍  Validating package.json...
[2/5] 🔍  Resolving packages...
[3/5] 🚚  Fetching packages...
error node-rules@7.1.0: The engine "node" is incompatible with this module. Expected version "10". Got "12.16.2"
error Found incompatible module.
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
```

**Comment by mithunsatheesh** [comment]
This should be resolved with the linked merge request. Please check.

**Comment by antarticuno** [comment]
Was this fully resolved btw? I do see the code change to the package.json in the linked merge request, but currently the latest version on npm (7.1.0) seems to still have the old node 10 engine setting. I'm still having a similar issue (using node 14), and am wondering if this could be resolved with a release/republish to npm?

**Comment by mithunsatheesh** [comment]
Hey @antarticuno . I just checked the referenced commit and the changes are in the published 7.1.0 version.
https://github.com/mithunsatheesh/node-rules/blob/master/package.json#L59

Can you please check the package.json file in the installed package in your package for node engine entries?

**Comment by antarticuno** [comment]
@mithunsatheesh  thanks so much for your response. I looked into the package.json and this is what I see. Can send screenshots too if you'd like

```
{
  "name": "node-rules",
  "version": "7.1.0",
  "description": "Business Rules Engine for JavaScript",
  "keywords": [
    "bre",
    "rete",
    "rule",
    "rules",
    "engine",
    "rule engine",
    "rules engine",
    "javascript rule engine",
    "js rule engine",
    "forward chaining rule engine",
    "inference system"
  ],
  "license": "MIT",
  "author": {
    "name": "Mithun Satheesh",
    "email": "mithunsatish@gmail.com"
  },
  "contributors": [
    {
      "name": "Abdul Munim Kazia",
      "email": "munim2020@gmail.com",
      "url": "http://munimkazia.com"
    },
    {
      "name": "ramanaveli2i",
      "url": "https://github.com/ramanaveli2i"
    }
  ],
  "repository": {
    "type": "git",
    "url": "https://github.com/mithunsatheesh/node-rules"
  },
  "dependencies": {
    "lodash.clonedeep": "^4.5.0",
    "lodash.isequal": "^4.5.0"
  },
  "devDependencies": {
    "core-js": "^3.15.2",
    "@babel/cli": "^7.14.5",
    "@babel/core": "^7.14.6",
    "@babel/eslint-parser": "^7.14.7",
    "@babel/preset-env": "^7.14.7",
    "@babel/register": "^7.14.5",
    "eslint": "^7.29.0",
    "colors": "^1.4.0",
    "coveralls": "^3.1.1",
    "jest": "^27.0.6",
    "jest-cli": "^27.0.6",
    "webpack": "^5.41.1",
    "webpack-cli": "^4.7.2"
  },
  "main": "index.js",
  "engines": {
    "node": "10"
  },
  "scripts": {
    "test": "jest",
    "build": "webpack",
    "cover": "jest --coverage",
    "coveralls": "npm run cover && coveralls < coverage/lcov.info"
  },
  "readmeFilename": "README.md"
}

```

**Comment by mithunsatheesh** [comment]
Hey @antarticuno Thanks for confirming this. Let me publish a new version from the mainline branch which seems to have this fixed. Will confirm here once done.

**Comment by mithunsatheesh** [comment]
@antarticuno published 7.2.0. 
Created a project and installed node-rules as dependency. I can see `>=0.10.3` in engines. Let me know.

**Comment by antarticuno** [comment]
Yup! Verified this as well on my end that the node-rules package.json has the correct `engines` value. Thank you so much for your assistance
